export interface IUtilReporte {
  formatoInforme: FormatoUtilReporte;
  reporteType: IUtilReporteDetail;
}
export interface IUtilReporteDetail {
  fechaReporte: string;
  codigoReporte: string;
  tituloReporte: string;
  usuario: string;
  compania: string;
  columnas: string[];
  contenidoColumnas: string[][];
}
export type FormatoUtilReporte = "PDF" | "EXCEL" | "CSV";

export enum reportCodeEnum {
  HECTAREAS = "RPTSAFF_069",
  HACIENDA_EMPACADORA = "RPTSAFF_001",
  HACIENDA_ZONA = "RPTSAFF_002",
  HACIENDA_SUBZONA = "RPTSAFF_003",
  MANTENIMIENTO_SECTOR = "RPTSAFF_004",
  INGRESO_LOTE = "RPTSAFF_005",
  TIPO_CONTALILIZACION = "RPTSAFF_006",
  MANTENIMIENTO_EQUIPOS_MAQUINARIAS = "RPTSAFF_007",
  MANTENIMIENTO_TIPO_VIVIENDA = "RPTSAFF_008",
  MANTENIMIENTO_TIPO_SOLICITUD = "RPTSAFF_008",
  MANTENIMIENTO_TIPO_PROCESO = "RPTSAFF_008",
  MANTENIMIENTO_TIPO_RUTA = "RPTSAFF_008",
  MANTENIMIENTO_ESTADOS = "RPTSAFF_008",
  MANTENIMIENTO_ACCION = "RPTSAFF_008",
  MANTENIMIENTO_TIPO_MOTIVO = "RPTSAFF_008",
  MANTENIMIENTO_TIPO_ACCION = "RPTSAFF_008",
  MANTENIMIENTO_LOCALIZACION = "RPTSAFF_009",
  HACIENDA = "RPTSAFF_010",
  HITO_MUESTREO = "RPTSAFF_011",
  MANTENIMIENTO_VIVIENDA = "RPTSAFF_012",
  MANTENIMIENTO_VEHICULO = "RPTSAFF_013",
  MANTENIMIENTO_FUMIGACION = "RPTSAFF_014",
  MANTENIMIENTO_COMEDOR = "RPTSAFF_015",
  MANTENIMIENTO_TIPO_LABOR = "RPTSAFF_016",
  MANTENIMIENTO_LABOR = "RPTSAFF_017",
  MANTENIMIENTO_LABORES_INCOMPATIBLES = "RPTSAFF_018",
  DEFECTO_LABOR = "RPTSAFF_019",
  COSTO_POR_TIPO_MUESTREO = "RPTSAFF_020",
  GRUPO_LABORES = "RPTSAFF_021",
  LABORES_POR_GRUPO = "RPTSAFF_022",
  LABORES_PRODUCTO = "RPTSAFF_023",
  MANTENIMIENTO_PLAGA = "RPTSAFF_024",
  TIPO_CAJA_PARA_PAGO = "RPTSAFF_025",
  LABOR_POR_TIPO_CAJA = "RPTSAFF_026",
  LABOR_GENERICA_POR_TIPO_CAJA = "RPTSAFF_027",
  ITEM_POR_TIPO_CAJA = "RPTSAFF_028",
  MANTENIMIENTO_LABOR_GENERICA = "RPTSAFF_029",
  LABOR_POR_LABOR_GENERICA = "RPTSAFF_030",
  HABILIDADES_TRABAJADOR = "RPTSAFF_031",
  UNIDADES_COMPARACION = "RPTSAFF_032",
  MATERIAL_ENFUNDE = "RPTSAFF_033",
  OPTIMO_MATERIALES = "RPTSAFF_034",
  TIPO_COMPONENTE = "RPTSAFF_035",
  ITEM_EO_VS_SAFF = "RPTSAFF_036",
  MANTENIMIENTO_PARAMETRO_PRODUCCCION = "RPTSAFF_037",
  MANTENIMIENTO_COLORES_CINTA = "RPTSAFF_038",
  MANTENIMIENTO_SEMANA_PERIODO = "RPTSAFF_039",
  MANTENIMIENTO_DEFECTO_CALIDAD = "RPTSAFF_040",
  MANTENIMIENTO_UNIDAD_EMPAQUE = "RPTSAFF_041",
  MANTENIMIENTO_TIPO_PLANTACION = "RPTSAFF_042",
  MANTENIMIENTO_ESTACIONALIDAD = "RPTSAFF_043",
  MANTENIMIENTO_ESTACIONALIDAD_POR_LOTE = "RPTSAFF_044",
  MANTENIMIENTO_ESTACIONALIDAD_POR_LOTE_HISTORICO = "RPTSAFF_045",
  MANTENIMIENTO_NUMERO_PROCESO = "RPTSAFF_046",
  MANTENIMIENTO_TARA = "RPTSAFF_047",
  MANTENIMIENTO_CAUSALES = "RPTSAFF_048",
  ESTACION_TENSIOMETRO = "RPTSAFF_049",
  MANTENIMIENTO_PARAMETRO_QUIMICOS_MUESTREOS = "RPTSAFF_050",
  SISTEMA_DRENAJE_POR_LOTE = "RPTSAFF_051",
  MANTENIMIENTO_PRODUCTO_FRUTA = "RPTSAFF_052",
  PRODUCTO_EMBARQUE = "RPTSAFF_053",
  MANTENIMIENTO_TIPO_PLASTICO = "RPTSAFF_054",
  CONTROL_CAMIONES = "RPTSAFF_055",
  BUQUE = "RPTSAFF_056",
  PUERTO = "RPTSAFF_057",
  TIPO_CAJA = "RPTSAFF_058",
  TIPO_EMBALAJE = "RPTSAFF_059",
  MANTENIMIENTO_MARCAS = "RPTSAFF_060",
  HOMOLOGACION_HACIENDA = "RPTSAFF_061",
  TIPO_DEFECTO = "RPTSAFF_062",
  DEFECTO = "RPTSAFF_063",
  TRANSPORTISTA = "RPTSAFF_064",
  MANTENIMIENTO_TRANSPORTE_POR_TRANSPORTE = "RPTSAFF_065",
  PARAMETROS_GENERALES = "RPTSAFF_066",
  BIOMETRICO_POR_HACIENDA = "RPTSAFF_067",
  MANTENIMIENTO_PARAMETROS_PESAJE = "RPTSAFF_068",
}

export interface IServiceBase {
  aplicativoId?: string;
  estacion?: string;
  fechaActualizacion?: Date;
  fechaCreacion?: Date;
  horaCreacion?: Date;
  horaActualizacion?: Date;
  menuId?: string;
  usuarioCreacion?: string;
  usuarioActualizacion?: string;
}
