import { HttpClient, HttpHeaders, HttpParams, HttpParamsOptions } from "@angular/common/http";
import { Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { environment } from "src/environments/environment";
import { IConsultaNivelesAprobacionResponse } from "./niveles-aprobacion.interface";

@Injectable({
	providedIn: "root",
})
export class NivelesAprobacionService {
	private apiUrlNivelAprobacion = environment.nivelAprobacionServiceES;

	constructor(private http: HttpClient) { }

	private httpOptions = {
		headers: new HttpHeaders({
			"Content-Type": "application/json",
		}),
	};

	public obtenerNiveleAprobaciones(): Observable<IConsultaNivelesAprobacionResponse> {
		// return this.http.get<IConsultaNivelesAprobacionResponse>(`${this.apiUrlNivelAprobacion}`);
		return this.http.get<IConsultaNivelesAprobacionResponse>(`${this.apiUrlNivelAprobacion}`);
	}

	// Con headers
	public filterNivelesAprobaciones(idTipoSolicitud: string, idTipoMotivo: string, idNivelDireccion: string, idTipoRuta: string, idAccion: string): Observable<IConsultaNivelesAprobacionResponse> {
		const fromObject: any = {
			id_tipo_sol: idTipoSolicitud,
			IdNivelDireccion: idNivelDireccion,
			id_tip_mot: idTipoMotivo === null ? 10000 : idTipoMotivo,
			id_tip_ruta: idTipoRuta === null ? 10000 : idTipoRuta,
			id_accion: idAccion === null ? 10000 : idAccion
		};

		const httpParams: HttpParamsOptions = { fromObject } as HttpParamsOptions;

		return this.http.get<IConsultaNivelesAprobacionResponse>(`${this.apiUrlNivelAprobacion}/aprobacionesporfiltro`, {
			params: new HttpParams(httpParams)
		});

		// return of({
		// 	"totalRegistros": 16,
		// 	"nivelAprobacionType": [
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 1,
		// 			"tipoRuta": "Areas Corporativas",
		// 			"idRuta": 1,
		// 			"ruta": "Primer Nivel de aprobación",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 1,
		// 			"idNivelAprobacionRuta": "JEFATURA",
		// 			"nivelAprobacionRuta": "JEFATURA",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-06-21T16:41:10.907"),
		// 			"fechaCreacion": new Date("2024-06-21T16:41:10.907"),
		// 			"usuarioCreacion": "",
		// 			"usuarioActualizacion": "",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 1,
		// 			"tipoRuta": "Areas Corporativas",
		// 			"idRuta": 2,
		// 			"ruta": "Segundo Nivel de Aprobación",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 2,
		// 			"idNivelAprobacionRuta": "GERENCIA MEDIA",
		// 			"nivelAprobacionRuta": "GERENCIA MEDIA",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-06-24T15:01:19.05"),
		// 			"fechaCreacion": new Date("2024-06-24T15:01:19.05"),
		// 			"usuarioCreacion": "",
		// 			"usuarioActualizacion": "",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 1,
		// 			"tipoRuta": "Areas Corporativas",
		// 			"idRuta": 3,
		// 			"ruta": "Tercer Nivel de Aprobación",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 3,
		// 			"idNivelAprobacionRuta": "GERENCIA DE UNIDAD O CORPORATIVA",
		// 			"nivelAprobacionRuta": "GERENCIA DE UNIDAD O CORPORATIVA",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-06-24T15:02:50.97"),
		// 			"fechaCreacion": new Date("2024-06-24T15:02:50.97"),
		// 			"usuarioCreacion": "",
		// 			"usuarioActualizacion": "",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 1,
		// 			"tipoRuta": "Areas Corporativas",
		// 			"idRuta": 4,
		// 			"ruta": "Cuarto Nivel de Aprobación",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 4,
		// 			"idNivelAprobacionRuta": "VICEPRESIDENCIA",
		// 			"nivelAprobacionRuta": "VICEPRESIDENCIA",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-06-24T15:03:24.753"),
		// 			"fechaCreacion": new Date("2024-06-24T15:03:24.753"),
		// 			"usuarioCreacion": "",
		// 			"usuarioActualizacion": "",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 3,
		// 			"tipoRuta": "Aprobadores Fijos",
		// 			"idRuta": 5,
		// 			"ruta": "RRHH Corporativo",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 5,
		// 			"idNivelAprobacionRuta": "Gerente de RRHH Corporativo",
		// 			"nivelAprobacionRuta": "Gerente de RRHH Corporativo",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-06-24T15:04:10.987"),
		// 			"fechaCreacion": new Date("2024-06-24T15:04:10.987"),
		// 			"usuarioCreacion": "",
		// 			"usuarioActualizacion": "",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 3,
		// 			"tipoRuta": "Aprobadores Fijos",
		// 			"idRuta": 6,
		// 			"ruta": "Remuneraciones",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 6,
		// 			"idNivelAprobacionRuta": "Comité de Remuneraciones",
		// 			"nivelAprobacionRuta": "Comité de Remuneraciones",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-06-24T15:04:32.03"),
		// 			"fechaCreacion": new Date("2024-06-24T15:04:32.03"),
		// 			"usuarioCreacion": "",
		// 			"usuarioActualizacion": "",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 1,
		// 			"tipoRuta": "Areas Corporativas",
		// 			"idRuta": 1,
		// 			"ruta": "Primer Nivel de Aprobación",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 31,
		// 			"idNivelAprobacionRuta": "JEFATURA",
		// 			"nivelAprobacionRuta": "JEFATURA",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-08-16T14:23:48.013"),
		// 			"fechaCreacion": new Date("2024-08-16T14:23:48.013"),
		// 			"usuarioCreacion": "MFILIAN",
		// 			"usuarioActualizacion": "MFILIAN",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 4,
		// 			"tipoRuta": "Ruta por Excepción",
		// 			"idRuta": 6,
		// 			"ruta": "Remuneraciones",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 32,
		// 			"idNivelAprobacionRuta": "Comité de Remuneraciones",
		// 			"nivelAprobacionRuta": "Comité de Remuneraciones",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-08-20T09:45:25.907"),
		// 			"fechaCreacion": new Date("2024-08-20T09:45:25.907"),
		// 			"usuarioCreacion": "MFILIAN",
		// 			"usuarioActualizacion": "MFILIAN",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 4,
		// 			"tipoRuta": "Ruta por Excepción",
		// 			"idRuta": 9,
		// 			"ruta": "Primer Nivel de Aprobación",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 33,
		// 			"idNivelAprobacionRuta": "JEFATURA",
		// 			"nivelAprobacionRuta": "JEFATURA",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-08-20T10:07:55.323"),
		// 			"fechaCreacion": new Date("2024-08-20T09:45:25.907"),
		// 			"usuarioCreacion": "MFILIAN",
		// 			"usuarioActualizacion": "MFILIAN",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 4,
		// 			"tipoRuta": "Ruta por Excepción",
		// 			"idRuta": 10,
		// 			"ruta": "Segundo Nivel de Aprobación",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 34,
		// 			"idNivelAprobacionRuta": "GERENCIA MEDIA",
		// 			"nivelAprobacionRuta": "GERENCIA MEDIA",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-08-20T10:07:55.34"),
		// 			"fechaCreacion": new Date("2024-08-20T09:48:55.62"),
		// 			"usuarioCreacion": "MFILIAN",
		// 			"usuarioActualizacion": "MFILIAN",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 4,
		// 			"tipoRuta": "Ruta por Excepción",
		// 			"idRuta": 13,
		// 			"ruta": "Tercer Nivel de Aprobación",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 35,
		// 			"idNivelAprobacionRuta": "VICEPRESIDENCIA",
		// 			"nivelAprobacionRuta": "VICEPRESIDENCIA",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-08-20T10:02:18.073"),
		// 			"fechaCreacion": new Date("2024-08-20T10:02:18.073"),
		// 			"usuarioCreacion": "MFILIAN",
		// 			"usuarioActualizacion": "MFILIAN",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 4,
		// 			"tipoRuta": "Ruta por Excepción",
		// 			"idRuta": 5,
		// 			"ruta": "RRHH Corporativo",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 36,
		// 			"idNivelAprobacionRuta": "Gerente de RRHH Corporativo",
		// 			"nivelAprobacionRuta": "Gerente de RRHH Corporativo",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-08-20T10:04:45.58"),
		// 			"fechaCreacion": new Date("2024-08-20T10:04:45.58"),
		// 			"usuarioCreacion": "MFILIAN",
		// 			"usuarioActualizacion": "MFILIAN",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 2,
		// 			"tipoRuta": "Unidades",
		// 			"idRuta": 5,
		// 			"ruta": "RRHH Corporativo",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 37,
		// 			"idNivelAprobacionRuta": "Gerente de RRHH Corporativo",
		// 			"nivelAprobacionRuta": "Gerente de RRHH Corporativo",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-08-20T10:14:54.463"),
		// 			"fechaCreacion": new Date("2024-08-20T10:14:54.463"),
		// 			"usuarioCreacion": "MFILIAN",
		// 			"usuarioActualizacion": "MFILIAN",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 2,
		// 			"tipoRuta": "Unidades",
		// 			"idRuta": 7,
		// 			"ruta": "Primer Nivel de Aprobación",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 38,
		// 			"idNivelAprobacionRuta": "JEFATURA",
		// 			"nivelAprobacionRuta": "JEFATURA",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-08-20T10:14:54.463"),
		// 			"fechaCreacion": new Date("2024-08-20T10:14:54.463"),
		// 			"usuarioCreacion": "MFILIAN",
		// 			"usuarioActualizacion": "MFILIAN",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 2,
		// 			"tipoRuta": "Unidades",
		// 			"idRuta": 8,
		// 			"ruta": "Segundo Nivel de Aprobación",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 39,
		// 			"idNivelAprobacionRuta": "GERENCIA MEDIA",
		// 			"nivelAprobacionRuta": "GERENCIA MEDIA",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-08-20T10:14:54.463"),
		// 			"fechaCreacion": new Date("2024-08-20T10:14:54.463"),
		// 			"usuarioCreacion": "MFILIAN",
		// 			"usuarioActualizacion": "MFILIAN",
		// 			"estado": "A"
		// 		},
		// 		{
		// 			"idTipoSolicitud": 1,
		// 			"idNivelDireccion": "ASISTENTE - TECNICO",
		// 			"nivelDireccion": "ASISTENTE - TECNICO",
		// 			"idTipoMotivo": 1,
		// 			"idTipoRuta": 2,
		// 			"tipoRuta": "Unidades",
		// 			"idRuta": 11,
		// 			"ruta": "Tercer Nivel de Aprobación",
		// 			"idAccion": 1,
		// 			"idNivelAprobacion": 40,
		// 			"idNivelAprobacionRuta": "GERENCIA DE UNIDAD O CORPORATIVA",
		// 			"nivelAprobacionRuta": "GERENCIA DE UNIDAD O CORPORATIVA",
		// 			"tipoSolicitud": "Requisición Personal",
		// 			"accion": "Crear posiciones",
		// 			"tipoMotivo": "",
		// 			"correo": "",
		// 			"fechaActualizacion": new Date("2024-08-20T10:14:54.463"),
		// 			"fechaCreacion": new Date("2024-08-20T10:14:54.463"),
		// 			"usuarioCreacion": "MFILIAN",
		// 			"usuarioActualizacion": "MFILIAN",
		// 			"estado": "A"
		// 		}
		// 	]
		// });
	}
}
