export class DetalleSolicitud {
	constructor(
		public idDetalleSolicitud: number = 0,
		public idSolicitud: string = "",
		public codigo: string = "",
		public valor: string = "",
		public estado: string = "",
		// public fechaRegistro: string = "",
		public fechaRegistro: Date | string = new Date(),
		public compania: string = "",
		public unidadNegocio: string = "",
		public codigoPosicion: string = "",
		public descripcionPosicion: string = "",
		public areaDepartamento: string = "",
		public localidadZona: string = "",
		public nivelDireccion: string = "",
		public centroCosto: string = "",
		public nombreEmpleado: string = "",
		public subledger: string = "",
		public reportaA: string = "",
		public nivelReporteA: string = "",
		public supervisaA: string = "",
		public tipoContrato: string = "",
		public departamento: string = "",
		public cargo: string = "",
		public jefeSolicitante: string = "",
		public responsableRRHH: string = "",
		public localidad: string = "",
		// public fechaIngreso: string = "",
		public fechaIngreso: Date | string = new Date(),
		public unidad: string = "",
		public puesto: string = "",
		public jefeInmediatoSuperior: string = "",
		public jefeReferencia: string = "",
		public cargoReferencia: string = "",
		// public fechaSalida: string = "",
		public fechaSalida: Date | string = new Date(),
		public puestoJefeInmediato: string = "",
		public subledgerEmpleado: string = "",
		public grupoDePago: string = "",
		public sucursal: string = "",
		public movilizacion: string = "",
		public alimentacion: string = "",
		public jefeAnteriorJefeReferencia: string = "",
		public causaSalida: string = "",
		public nombreJefeSolicitante: string = "",
		public misionCargo: string = "",
		public justificacion: string = "",
		public sueldo: string = "",
		public sueldoVariableMensual: string = "",
		public sueldoVariableTrimestral: string = "",
		public sueldoVariableSemestral: string = "",
		public sueldoVariableAnual: string = "",
		public correo: string = "",

		public aprobadoresDinamicos:
			| string
			| null = "Descripción de aprobadores dinámicos",
		public gerenteRRHHCorporativo:
			| string
			| null = "Descripción de Ggrente de RRHH Corporativo",
		public comiteRemuneraciones:
			| string
			| null = "Descripción de Comité de Remuneraciones"
	) { }
}
